version: "3.5"

services:
  email:
    build: .
    container_name: email_microservice
    working_dir: /var/www/html/email_microservice
    networks:
      - email_network
    volumes:
      - ./:/var/www/html/email_microservice

  nginx:
    image: nginx:1.15
    container_name: email_nginx
    working_dir: /var/www/html/email_microservice
    networks:
      - email_network
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/email_microservice
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

networks:
  email_network:
    driver: bridge
